name: Publish NPM Package
on:
  workflow_run:
    workflows: ['Create Release']
    types:
      - completed
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@latest
      - name: Setup Node
        uses: actions/setup-node@latest
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build
        run: npm ci && npm run build
      - name: Publish package on NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
